version: "3"

# define the network
networks:
  web-network:
    driver: bridge

# start the services section
services:
  web:
    image: ludus/sample
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - mysql
    ports:
      - "5000:80"
    volumes:
      - web:/app
    networks:
      - web-network
  mysql:
    image: mysql:5.7.22
    environment:
      - "MYSQL_DATABASE=ludus"
      - "MYSQL_USER=teste"
      - "MYSQL_PASSWORD=teste"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - web-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - 50:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - web-network

volumes:
  web:
  mysql-data: